version: "3.9"

services:
  haproxy:
    build:
      context: haproxy
      dockerfile: Dockerfile
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - zero
    ports:
      - "8785:80"
  static_a:
    build:
      context: static-svc
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - zero
  static_b:
    image: ealen/echo-server
    environment:
      - PORT=3000
    networks:
      - zero

networks:
  zero:
    driver: bridge
